studentid= int(input("Enter student id: "))
Name= input("Enter student Name: ")
Marks= float(input("Enter Marks scored: "))
print("ID: ",studentid)
print("Name: ",Name)
print("Marks scored: ",Marks)
